SELECT *
FROM DBO.INDICADORES
WHERE CONCAT(C_ESTADO, C_MNPIO) IN ('1554', '914', '1588', '917', '178')
ORDER BY C_ESTADO, C_MNPIO



SELECT C_ESTADO, C_MNPIO, COUNT(*)
FROM DBO.INDICADORES
GROUP BY C_ESTADO, C_MNPIO
HAVING COUNT(*) > 1

SELECT * FROM DBO.HOUSE_PRICES
SELECT * FROM DBO.INDICADORES
SELECT * FROM DBO.STATES_COORDS
SELECT * FROM DBO.HOUSE_DATA